[package]
name = "starship-preset-combiner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
reqwest = "0.12.15"
tokio = { version = "1.44.1", features = ["full"] }
