services:
  wiremock:
    # https://wiremock.org/docs/standalone/docker/
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - 8080:8080
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint:
      - "/docker-entrypoint.sh"
      - "--global-response-templating"
      - "--disable-gzip"
      - "--verbose"
      - "--disable-banner"
